### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by codeuriii** [Youvataque/HomeFlix-discontinued#1]
Hello ! J'ai vu ta publication sur le forum, si tu veux je peux t'aider au développement, si jamais il y a des choses a rajouter ou des problèmes a régler. J'ai moi même de l'expérience avec flutter et dart.

**Comment by codeuriii** [comment]
Aussi tu fera gaffe il reste des path en dur dans ton code

**Comment by Youvataque** [comment]
Ah c'est super gentil merci ^^. J'apprecierait oui si tu le souhaites on peut continuer à discuter sur une platforme plus adapté mon discord : youvataque#8947.

**Comment by Youvataque** [comment]
> Aussi tu fera gaffe il reste des path en dur dans ton code

Ah c'est super gentil merci ^^. J'apprecierait oui si tu le souhaites on peut continuer à discuter sur une platforme plus adapté mon discord : youvataque#8947.
